CREATE TABLE "LOAD_DATA"."PUBLIC"."SAMPLE_ORDERS_UI" 
( 
    ORDER_ID NUMBER(38, 0) , 
    TRUCK_ID NUMBER(38, 0) , 
    LOCATION_ID NUMBER(38, 0) , 
    CUSTOMER_ID NUMBER(38, 0) , 
    DISCOUNT_ID VARCHAR , 
    SHIFT_ID NUMBER(38, 0) , 
    SHIFT_START_TIME TIME , 
    SHIFT_END_TIME TIME , 
    ORDER_CHANNEL VARCHAR , 
    ORDER_TS TIMESTAMP_NTZ , 
    SERVED_TS VARCHAR , 
    ORDER_CURRENCY VARCHAR , 
    ORDER_AMOUNT NUMBER(38, 4) , 
    ORDER_TAX_AMOUNT VARCHAR , 
    ORDER_DISCOUNT_AMOUNT VARCHAR , O
    RDER_TOTAL NUMBER(38, 4) 
    ); 

CREATE TEMP FILE FORMAT "LOAD_DATA"."PUBLIC"."temp_file_format_2026-02-18T16:31:28.527Z"
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO "LOAD_DATA"."PUBLIC"."SAMPLE_ORDERS_UI" 
FROM (SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
	FROM '@"LOAD_DATA"."PUBLIC"."__snowflake_temp_import_files__"') 
FILES = ('2026-02-18T16:28:09.287Z/sample_orders.csv') 
FILE_FORMAT = '"LOAD_DATA"."PUBLIC"."temp_file_format_2026-02-18T16:31:28.527Z"' 
ON_ERROR=ABORT_STATEMENT 
-- For more details, see: https://docs.snowflake.com/en/sql-reference/sql/copy-into-tablesno